services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"


  demo2026:
    image: demo2026
    build: ../
    container_name: demo2026
    ports:
        - "8080:8080"