services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27020:27017"


  api_monstres:
    build: ../
    container_name: api_monstres
    ports:
        - "8083:8080"